<MatrixCell>:
    cell_font_size: max(root.min_cell_font_size, min(root.max_cell_font_size, min(root.height * root.font_height_ratio, root.width * root.font_width_ratio)))

    border_color: (1, 0, 0, 1) if root.is_empty else (1, 1, 1, 1)

    FloatLayout:

        Label:
            text: root.dextro_text if root.is_empty or root.is_header else ""
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            opacity: 1 if root.is_empty or root.is_header else 0
            font_size: root.cell_font_size

        Button:
            text: root.dextro_text if not root.is_empty and not root.is_header else ""
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            opacity: 1 if not root.is_empty and not root.is_header else 0
            disabled: root.is_empty or root.is_header
            font_size: root.cell_font_size
            on_release: root._show_card_details()